function [realvalue,rlocation] = PSOforfinal(ybar,tbar,Sn,D11,D22,D33,D12,D13,D23,Fs)
nDim = 3;

rmin=[0      0     -pi/2];  %w0, alpha, delta
rmax=[Fs*pi   2*pi   pi/2];



fitFuncParams = struct('rmin',rmin,...
                           'rmax',rmax,...                           
                           'Data',ybar,...
                           't',tbar,...
                           'Sn',Sn,...
                           'D11',D11,...
                           'D22',D22,...
                           'D33',D33,...
                           'D12',D12,...
                           'D13',D13,...
                           'D23',D23);%,...
                           %'Fs',Fs);
fitFuncHandle = @(x) fitnessfuctionforpso(x,fitFuncParams);

psoOut = ldacpso(fitFuncHandle,nDim);
a1=psoOut.bestLocation;
[realvalue,rlocation]=fitnessfuctionforpso(a1,fitFuncParams);
end




